language: go
go:
- 1.x
- "1.10"
- 1.12.x
- master
before_install:
- go get github.com/mattn/goveralls
script:
- go test -v -covermode=count -coverprofile=coverage.out ./rp
- "$GOPATH/bin/goveralls -service=travis-ci"
env:
  global:
    secure: VRq/cxVdJjpCgmioB6AqUGjWrd8jOFXGaIsBdrEqgEQqAK6gNqpuWu+e88DQli1QFsIMC7IS9aiBmdpCLobpPD+BPRAiYB4IJKTWSdCl7YTYQD89jqxoEB0idxGk6mtObZjfGNIoM/AMDwMcX9XuyEuvHTl9p4bM+cr6sh9sZ4mFjguDEjr0w6RKYftxyAEbo3RAkCsBzitW2b0fgMgG/mNLfnleui8QPNDnNz1C3V8+CJwSra7pXZCOfMIYwvUtvJB6/JthL+Q5UNzAmJcR7X0MBzJmLdPx2r9XAKRwUHp+tvLtimgyzQ/2Z1h5D/+25rk9T9V0OhzEM8l4FMXeZ4EJsltF2f8sCrCeN9E06qcgc26Gq3wf6rnGR+gwH6+HgslfiI9AuA1tYxoluZXIIDyVwn/b4kYrrepHYER9XeHj7iRdyNptKAuwGaWpTZIYd57+slAXKykhOXpHzVDfg1BjjBgL9kY2Xw+9W8pe0ZxEYO0LWocFfkTCGWIhJzNxUzsrXkKq/BetenMzVT3R6iifpZOvLWCRr0kYpEShg0NhQb3k/t+eYDbrJlgeP32u4ziEeAFD72JNac+kJBcnTKIbCybq12hyE0AeQnLZGdaGkRA8OaN9qgoIFojeSItnZs0wbhwlnJ6fiymRqC9f/xfAyTZJVVVGL+fHgDcheZI=
